In [1]:
import numpy as np

In [2]:
a = np.zeros((4,5)) #0으로 구성된 4*5 행렬 생성

In [3]:
a[:,:] = 1    #모든 원소를 1로 변환

In [4]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
a[0:2,:] = 2    #일부만 변환 가능. dataframe과 달리, 각 열이 먼저 인덱스됨에 주의

In [6]:
a

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
a += 1    #broadcasting 기능 동작 가능

In [8]:
a

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [9]:
np.mean(a, axis = 0)    #평균 구하기, axis = 0  :열, 1  :행

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
m = a>2

In [11]:
a[m]   #마스킹

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [12]:
a[[1,2],:] #1,2행 전체를 표시

array([[3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2.]])

In [13]:
a[:,[1,2]]

array([[3., 3.],
       [3., 3.],
       [2., 2.],
       [2., 2.]])

In [14]:
a[[1,2],[1,2]]

array([3., 2.])